### ISSUE TITLE
DijkstraMap can't find path

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#161] opened 2017-06-17 17:45 UTC
Using a shadowmap FOV a subset of map cells are found and all non-visible cells are marked as blocked for the DijkstraMap instance. Not all visible cells are shown to have a path.

![path found](https://user-images.githubusercontent.com/1217477/27255023-f7e0952a-5349-11e7-903d-c772e6ca3f92.png)

![path not found](https://user-images.githubusercontent.com/1217477/27255025-fc906c3a-5349-11e7-9cd0-e787480f305e.png)

**Comment by tommyettinger** [comment] 2017-06-17 20:20
Show some code, please. I'd be like the LibGDX people and insist on an SSCE, but that would be rude.

**Comment by SquidPony** [comment] 2017-06-17 20:28
It's all tangled up in Epigon, lemme see what I can chunk out

**Comment by SquidPony** [comment] 2017-06-17 21:36
This might be related to a problem I'm having with blocking coords not being respected as expected.

fovResult is a previously calculated result which visually is correctly showing up as seen in the pictures above

`
    private Collection<Coord> calculateBlocked() {
        Set<Coord> blocked = new HashSet<>();
        for (int x = 0; x < BIG_MAP_WIDTH; x++) {
            for (int y = 0; y < BIG_MAP_HEIGHT; y++) {
                if (fovResult[x][y] <= 0) {
                    blocked.add(Coord.get(x, y));
                }
            }
        }
        return blocked;
    }
`

**Comment by tommyettinger** [comment] 2017-06-17 22:06
I'm not totally sure what the issue is here, though there could absolutely be one. It is possible that a cell may be visible but there's no path to it; I may be able to see across a chasm but not jump over it. I don't know what YES and NO are supposed to mean here; did you hover the mouse, or some similar pathfinding thing, over "NO" and it didn't get a path to it? Could this be related to mouse position not being mapped correctly to grid positions?

**Comment by SquidPony** [comment] 2017-06-17 22:20
I hovered the mouse over the bottom position and didn't get a path even though hovering over the position above (the "yes" and top picture) shows that the tile right above is walkable.

Mouse to map seems to work correctly when there's no FOV going on. The problem could easily be that I'm just not linking them correctly.

**Comment by SquidPony** [comment] 2017-06-18 01:00
So I did in fact have the fov recalc in the update render loop which added weirdness, but even with that fixed I'm seeing that behavior. In the picture below the tiles to the SE should be highlightable as pathable but they're not when moused over.  It only seems to happen when there's a tight squeeze along the path.

![squeeze](https://user-images.githubusercontent.com/1217477/27257327-dfca5290-5386-11e7-98f8-83da6ad91937.png)

**Comment by tommyettinger** [comment] 2017-06-18 03:20
I fixed this in your code that you hide from prying eyes. It isn't a SquidLib bug, so I'll close the issue, but if anyone comes across this later:

The issue happens when impassable cells are derived from anything not in FOV, and only is caused by FOV being recalculated at the wrong time(s). This can be avoided by calculating the currently visible cells at the end of each player movement (by one cell), but before recalculating the impassable cells or the Dijkstra map using those impassable cells (also done at the end of each player movement, but after FOV calculations).

**Closed by tommyettinger** 2017-06-18 03:20 UTC
Labels: bug
