### ISSUE TITLE
SquidLib setup tool took 2 "Generate" runs before it worked right

### ISSUE THREAD

**Issue by SquidPony** [SquidPony/SquidLib#112] opened 2016-02-13 18:32 UTC
The first time it failed on a move file error.

Here's the log:

Generating app in F:\Projects\AF-SL3
Executing 'F:\Projects\AF-SL3/gradlew.bat clean --no-daemon'
Downloading http://services.gradle.org/distributions/gradle-2.4-all.zip
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping C:\Users\Eben Howard\.gradle\wrapper\dists\gradle-2.4-all\4nbr1pmuf9qag6p78oj1edfbtn\gradle-2.4-all.zip to C:\Users\Eben Howard\.gradle\wrapper\dists\gradle-2.4-all\4nbr1pmuf9qag6p78oj1edfbtn
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html.
Configuration on demand is an incubating feature.
Download https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.pom
Download https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.jar

FAILURE: Build failed with an exception.

\* What went wrong:
A problem occurred configuring root project 'AF-SL3'.
\> Could not resolve all dependencies for configuration ':classpath'.
   \> Could not download gwt-gradle-plugin.jar (de.richsource.gradle.plugins:gwt-gradle-plugin:0.6)
      \> Could not get resource 'https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.jar'.
         \> Failed to move file 'C:\Users\Eben Howard\AppData\Local\Temp\gradle_download8290871543128982230bin' into filestore at 'C:\Users\Eben Howard\.gradle\caches\modules-2\files-2.1\de.richsource.gradle.plugins\gwt-gradle-plugin\0.6\7393243331d33bbf6fde148da090500249be9e53\gwt-gradle-plugin-0.6.jar' 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 40.984 secs
Done!
To import in Eclipse: File -> Import -> Gradle -> Gradle Project
To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...
Generating app in F:\Projects\AF-SL3
Executing 'F:\Projects\AF-SL3/gradlew.bat clean --no-daemon'
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html.
Configuration on demand is an incubating feature.
Download https://jcenter.bintray.com/de/richsource/gradle/plugins/gwt-gradle-plugin/0.6/gwt-gradle-plugin-0.6.jar
:core:clean UP-TO-DATE
:desktop:clean UP-TO-DATE
:html:clean UP-TO-DATE

BUILD SUCCESSFUL

Total time: 5.568 secs
Done!
To import in Eclipse: File -> Import -> Gradle -> Gradle Project
To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...

**Comment by SquidPony** [comment] 2016-02-13 18:44
After removing that project and regenerating, I got a different failed build, although again a second push of the generate button appears to have worked.

log:

Generating app in F:\Projects\AF-SL3
Executing 'F:\Projects\AF-SL3/gradlew.bat clean --no-daemon'
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: http://gradle.org/docs/2.4/userguide/gradle_daemon.html.

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at http://gradle.org/docs/2.4/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Done!
To import in Eclipse: File -> Import -> Gradle -> Gradle Project
To import to Intellij IDEA: File -> Open -> build.gradle
To import to NetBeans: File -> Open Project...

**Comment by tommyettinger** [comment] 2016-02-13 19:38
The first error seems to be caused by a network issue when downloading a plugin that the HTML output requires. HTML output seems to be broken in Beta 3, and I've been trying to figure out ways to test it. @smelc has gotten HTML fully working with GWT 2.7, I think I've managed to push the dependency level down to 2.6 so we are compatible with libGDX's defaults, but HTML has never worked for me for incomprehensible reasons. I have an idea though... I will check if the distance field fonts are a problem on HTML since they require a shader, and the WebGL that libGDX uses may not support all the features desktop OpenGL does. I'll create an issue for broken HTML in Beta 3 and mark it as fixed once there's a final release that solves it for certain.
The second failure is odd since it requests `--no-daemon` and then errors starting up the daemon that it was not supposed to use... I've had issues myself with Gradle creating daemons and not cleaning them up or reusing them. I don't think that's actually a flaw with the setup tool's code, though I hope I can fix it somehow. It seems to be part of the Gradle territory, which remains a mostly good tool for managing multiple, including non-desktop, targets.

**Comment by tommyettinger** [comment] 2016-03-15 00:40
I think this may be out of the domain of the setup tool's fix-able code. The first outage may have been related to JVM memory issues, anti-virus blocking a network request, the network connection to Maven Central being down briefly, or any number of other issues that I don't think I can figure out from here. The master-version setup tool should behave differently in some ways, and even though it will definitely be slower since jitpack.io needs to build SquidLib from source when a new snapshot commit is requested, it should be better for keeping up-to-date. I'm closing, but am "open" to re-opening it if we can figure out that it is a code problem.

**Closed by tommyettinger** 2016-03-15 00:40 UTC
Labels: bug
