### ISSUE TITLE
FOV - shadowcasting seems to be broken for infinite radius

### ISSUE THREAD

**Issue by davidbecker** [SquidPony/SquidLib#65] opened 2015-08-23 19:24 UTC
I played around with this library a little and noticed the following:
I created a new Dungeon with DungeonGenerator and an input map with the dimensions 60*40. There weren't any other settings set, so it is a fairly open map.

When I now compute the FOV(created with new FOV(FOV.SHADOW) ) with:

``` java
double[][] calculateFOV(double[][] resistanceMap, int startx, int starty)
```

my game becomes unresponsive after a few turns. I don't run into problems when I create the FOV object with new FOV(FOV.RIPPLE) or when I use

``` java
double[][] calculateFOV(double[][] resistanceMap, int startX, int startY, double radius, Radius radiusTechnique)
```

with shadow casting and fairly conservative settings (radius = 8, radiusTechnique=Radius.DIAMONT)

**Comment by tommyettinger** [comment] 2015-08-24 05:48
Hm, can you investigate the resistance map? If it was generated from the dungeon using `DungeonUtility.generateResistances(char[][])`, and the `char[][]` is from DungeonGenerator, then the map should be bounded (1.0 or greater for walls and walls around all edges). I didn't write the shadowcasting code, and I don't claim to really know how it works, but I suspect that if the map is not bounded it may have issues when range is infinite. I do suspect that there may be bugs in FOV still, I fixed a strange one recently that related to `Radius.SQUARE` being used for (as far as I could tell) any FOV.  What's odd is that it works for a few turns and only then becomes unresponsive. Is there some circumstance that could be reliably occurring on the last turn you can take? Like moving so you have a clear line to an unbounded edge/corner? Could it be stuck in an FOV-related loop in your code (or about as likely, SquidLib code)? Does using a radius that is rather large (let's say 100 here, larger than would be needed for your map) cause the same problem an infinite radius does? It's also possible that (and I don't actually know how shadowcasting works, @SquidPony wrote it) shadowcasting may work inward from a circle with the given radius, which would need some checks that it may already do (like not extending past the bounds of the map) to avoid processing approximately `2^31 * 2 * pi` ines if given a maximum-possible-`int` radius. I'll give a look into the shadowcasting code to at least see if it's adequately checking how much work it should do for infinite-distance FOV.

**Comment by smelc** [comment] 2015-08-24 07:21
First, thank you @tommyettinger for you work on squidlib, it is a pleasure to have such a library freely available !

I witness this bug often too, in squidlib 2.3.1 (and I was about to update to 2.9 to see if it got fixed); and it seems to me the algorithm is going outside the map. Like @dasmau89, I use `DungeonGenerator`, without any options. Here's a screenshot where I hit the bug (fov slightly affects the color of walls: visible walls are redish):

![loop](https://cloud.githubusercontent.com/assets/634720/9434563/993200fe-4a40-11e5-9003-c6c6948422e1.png)

The only modification I made to the generated map is the Ω on the bottom left, but it is not used for the map used to compute the FOV, and it isn't visible from @'s position. I believe the algorithm is going outside the map, because here are the variables I see in the debugger (see `currentX` and `currentY`):

![loop-vars](https://cloud.githubusercontent.com/assets/634720/9434596/cb84fc64-4a40-11e5-8d92-848693d98217.png)

while my stacktrace is:

~~~~ {.java}
	FOV.shadowCast(int, double, double, int, int, int, int) line: 319	
	FOV.shadowCast(int, double, double, int, int, int, int) line: 347	
	FOV.calculateFOV(double[][], int, int, double, Radius) line: 225	
	FOV.calculateFOV(double[][], int, int, int) line: 168	
	FOV.calculateFOV(double[][], int, int) line: 149	
~~~~

**Comment by dasmau89** [comment] 2015-08-24 12:07
@tommyettinger I didn't create the resistance map with DungeonUtil, but filled it when I parsed the map "by hand" with 1.0 for '#' and 0.0 for '.' - which should result in the same array. I will change this part of my code to use DungeonUtil when I get home and report back.

**Comment by tommyettinger** [comment] 2015-08-25 00:39
Thanks for the hotfix, @dasmau89 , I have it committed with one update (a 60x40 grid with no obstacles needs more than 60 radius to reach from corner to corner with Euclidean or Manhattan distance, but you're right that the width and height are the answer; I believe width + height should be enough every time for shadowcasting). I'm leaving this open until I can confirm that this reliably fixes the near-infinite looping...

**Comment by SquidPony** [comment] 2015-09-20 19:03
I think I caused this bug when I changed how radius worked a while ago testing making shadowcasting directly work with transparency. I'll run some tests to confirm it's working correctly now though, thanks for the fix @dasmau89!

**Comment by tommyettinger** [comment] 2017-02-22 05:02
Can you let us know what the story is with this bug, @SquidPony ? Is it still an issue or can we close?

**Comment by SquidPony** [comment] 2017-06-17 14:39
confirmed that this is all fine now

**Closed by SquidPony** 2017-06-17 14:39 UTC
Labels: bug, high priority
