### ISSUE TITLE
ArrayIndexOutofBoundsException with SerpentDeepMapGenerator

### ISSUE THREAD

**Issue by Taffaz** [SquidPony/SquidLib#115] opened 2016-02-19 15:22 UTC
I'm been running into an intermittent crash with my game that I've narrowed down to the SerpentDeepMapGenerator. It is crashing out at the posToHilbert method during the generation and the rng seed is what was causing it to happen intermittently. When I changed the rng to have a constant seed of "test" it crashed every time whereas "test2" ran without issue.

I get the following stack trace.

```
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: -447
    at squidpony.squidmath.CoordPacker.posToHilbert(CoordPacker.java:4077)
    at squidpony.squidmath.CoordPacker.queryPacked(CoordPacker.java:1191)
    at squidpony.squidgrid.mapping.SerpentDeepMapGenerator.generate(SerpentDeepMapGenerator.java:367)
    at com.taffaz.testgame.TaffazGame2.create(TaffazGame2.java:26)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:147)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)

```

To replicate it I created a new Game class by deleting everything in the BasicDemo and deleted everything in create() and replaced it with this:

```
@Override
    public void create() {
        gridWidth = 80;
        gridHeight = 32;
        rng = new RNG("test");

        SerpentDeepMapGenerator mapGen = new SerpentDeepMapGenerator(gridWidth, gridHeight, 10, rng);
        mapGen.generate();
    }
```

**Comment by tommyettinger** [comment] 2016-02-20 00:14
I think I know what causes/caused this, and I am moderately sure I changed something recently in the master revision to fix that problem. I'm investigating now; are you using 3.0.0-b3 or master? I'll test on both, which could give me an idea of where the problem is.

I haven't updated the Readme yet, but there is a new version of the setup tool that downloads a fresh build of the master revision of the code instead of depending on releases. If you are currently using 3.0.0-b3, maybe try the jar at https://github.com/tommyettinger/SquidSetup/releases/tag/v3.0.0-LATEST for building with the fix that I either will commit for this issue or have possibly already committed.

**Comment by tommyettinger** [comment] 2016-02-20 01:19
This seems to be fixed as of the current latest commit; the code I thought fixed it instead fixed a different issue, haha yay, all these space-filling curves are melting my mind. There was a Deep-specific issue with 3D Moore Curves (since only SerpentDeepMapGenerator makes a 3D dungeon layout, only it was affected) that I thought was the culprit and had fixed earlier. This issue turned out to be different and not actually isolated to SerpentDeepMapGenerator, since there was some copied loop code that went in reverse order for part of the row and column positions. This order turned out to matter quite a bit, since it could subtract a large value from a small position if the RNG had made the row/column widths in just the "right" way, and so produce a negative position... that would then be looked up as an array index in the Hilbert Curve/Moore Curve stuff in CoordPacker. And of course a negative index in an array throws the Exception you have been getting... The Serpent map generators tweak room size by generating a large random number, using sections of its bits to enlarge rooms by that random value, and shrinking the whole of the room sizes by a factor related to how many bits are set in the number. If the random number had certain bits set in a "lop-sided" way, where some bit pattern makes (I'm guessing here) more room enlargement on the right half of the map or bottom half but not the left half or top half, the code before the fix might have produced negative positions when those random numbers were generated. Judging by the few minutes of continuous dungeon generation I've tried, this seems fixed now in the master revision, which the previously linked jar will download.

I'm surprised it took this long for the bug to show up, actually, I haven't tested a whole lot of seeds but there must be some number or bit pattern in a larger number that was generated by at least the seeds you encountered issues with. It would be nice if there was a sane way to test RNG-sensitive code for a large number of seeds, but there's 18,446,744,073,709,551,614 values possible for a 64-bit number like LightRNG's seeds (which RNG now defaults to internally, since LightRNG is very, very fast), so it might take a while to find any problematic ones...

**Comment by Taffaz** [comment] 2016-02-20 09:39
Great, thanks for the update. I may have to spend some time looking more in depth at the different generations as it's just a black box for me. I assume I can just update my gradle build file to update to the latest? Or will I have to make a new project and copy across my files? Not really an issue either way but just curious.

**Comment by tommyettinger** [comment] 2016-02-20 11:00
I would personally make a new project with the 3.0.0-LATEST version of SquidSetup, since it's the least work unless your build.gradle has been given a lot of changes. A second option if you've customized your build.gradle might be to make a new sample project with that "LATEST" setup tool, check where things have changed in the fresh build.gradle, and copy over the changed sections into your customized one, like dependency versions and a few other things. Repositories are different in one of the lists of repositories, adding jitpack.io as a place to look for dependencies. That site, jitpack.io, builds libraries from source for snapshot versions. The actual dependency string for squidlib and squidlib-util, wherever they show up, changed so it points to the snapshot on jitpack.io instead of the release on maven central. LibGDX's version I think increased since there was a bugfix release. Maven central is a hassle to get a new release up often, so jitpack is a huge help here, and I'm very happy with it so far. If you're interested in targeting HTML, the projects made by 3.0.0-LATEST will have a number of other fixes, and I don't think the HTML projects generated by 3.0.0-b3 even work out of the box, so if you want HTML, absolutely make a fresh project and copy code over.

I'll close the issue if this latest update fixes the problem without introducing a new one somewhere.

As an aside, what kind of game are you making with SquidLib? I'm really happy that someone's using the Deep mapgen, since it's one of a few things that currently only SquidLib supports to my knowledge, and it was a fun class to make. Are there any requests for features you might want to see, maybe in the dungeon generation?

**Comment by Taffaz** [comment] 2016-02-20 14:19
I'm just making a test game to implement all the features I'm going to put in the tutorial so just a standard dungeon crawl. I used the deep map gen as it was easy to get a multi level map to test out mob spawning and dealing with z levels.

**Comment by tommyettinger** [comment] 2016-11-17 23:24
It looks like this is fixed, so I'll close this issue. Deep map generation could probably be more robust, but for reasonably-sized maps (more than 50x50x8 or so) it should be fine in general.

**Closed by tommyettinger** 2016-11-17 23:24 UTC
